name: PlanF production deployment

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_deploy_to_lightsail_container_service:
    runs-on: ubuntu-latest

    env:
      SERVICE_NAME: ${{ secrets.SERVICE_NAME_PRODUCTION }}
      APP_KEYS: ${{ secrets.APP_KEYS_PRODUCTION }}
      API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
      TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}
      ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      NODE_ENV: production
      MAILJET_PUBLIC_KEY: ${{ secrets.MAILJET_PUBLIC_KEY }}
      MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}
      S3_REGION: ${{ secrets.S3_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}


    steps:
    - uses: actions/checkout@v3

    - name: Upgrade AWS CLI version and setup lightsailctl
      run: |
       aws --version
       curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
       unzip awscliv2.zip
       sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
       which aws
       aws --version
       sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
       sudo chmod +x /usr/local/bin/lightsailctl

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build strapi image
      run: >
        docker build .
        --file ./Dockerfile
        --tag public.ecr.aws/n0p8j4k5/plan-f/cms:${GITHUB_SHA}

    - name: Push the app image
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n0p8j4k5/
        docker push public.ecr.aws/n0p8j4k5/plan-f/cms:${GITHUB_SHA}

    - name: Create container_with_image.yml
      run: |
        cat .github/workflows/planf-container.yml.tpl | envsubst > container_with_image.yml
        cat container_with_image.yml

    - name: Deploy to Lightsail
      run: >
        aws lightsail create-container-service-deployment
        --cli-input-yaml file://container_with_image.yml
        --output yaml
